version: '3.8'
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=evgheni.calcutin@gmail.com
      - RENEWAL_INTERVAL=1d
      - DEBUG=1
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
  website:
    image: resume
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

volumes:
  letsencrypt:
