version: "3.8"
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=evgheni.calcutin@gmail.com
      - RENEWAL_INTERVAL=1d
      - DEBUG=1
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d

  website:
    image: ecalcutin/kalkutin.dev-website
    restart: always
    ports:
      - 8080:80

  ghostblog:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8000:2368
    depends_on:
      - ghostdb
    volumes:
      - ./ghostdata:/var/lib/ghost
    environment:
      database__client: mysql
      database__connection__host: ghostdb
      database__connection__database: ghost
      database__connection__user: ${GHOST_DB_USER}
      database__connection__password: ${GHOST_DB_PASS}
      url: https://blog.kalkutin.dev
      #NODE_ENV: development

  ghostdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_PASS}

volumes:
  letsencrypt:
