server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name kalkutin.dev www.kalkutin.dev;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/kalkutin.dev/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/kalkutin.dev/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/kalkutin.dev/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    gzip on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 0;
    gzip_types text/plain application/javascript text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype;

    location ~* \.(?:eot|woff|woff2|ttf|svg|otf|js|css) {
        access_log        off;
        log_not_found     off;
        expires           10m;
        add_header        Cache-Control "public";
        add_header        Access-Control-Allow-Origin *;
        types     {font/opentype otf;}
        types     {application/vnd.ms-fontobject eot;}
        types     {font/truetype ttf;}
        types     {application/font-woff woff;}
        types     {font/x-woff woff2;}
        types     {image/svg+xml svg svgz;}
    }

    location / {
        proxy_pass http://website;
    }
}