apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: applications
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
