name: Build and deploy application

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ecalcutin/resume

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Increment version
        id: increment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          VERSION=$(npm version patch)

          git push --follow-tags
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [increment-version]
    outputs:
      image_tag: ${{ needs.increment-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull latest changes
        run: git pull origin main
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ needs.increment-version.outputs.version }} .
          docker push ${{ env.IMAGE_NAME }}:${{ needs.increment-version.outputs.version }}
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.increment-version.outputs.version }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-k8s.yaml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
