name: Build and deploy

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ecalcutin/kalkutin.dev

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Increment version
        id: increment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          VERSION=$(npm version patch --no-git-tag-version)

          git add package.json
          git commit -m "Bump version to $VERSION [skip ci]"
          git push
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [increment-version]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ needs.increment-version.outputs.version }} .
          docker push ${{ env.IMAGE_NAME }}:${{ needs.increment-version.outputs.version }}
  # deploy-to-cluster:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install kubectl
  #       uses: azure/setup-kubectl@v4
  #       with:
  #         version: v1.32.4
  #     - name: Configure Kubeconfig
  #       uses: azure/k8s-set-context@v4
  #       with:
  #         method: service-account
  #         k8s-url: https://cluster.kalkutin.dev:6443
  #         k8s-secret: ${{ secrets.KUBE_TOKEN }}
  #     - name: Deploy to cluster (dev)
  #       run: |
  #         cd k8s/overlays/dev
  #         kustomize edit set image $IMAGE_NAME=ecalcutin/kalkutin.dev:$GITHUB_SHA
  #         kubectl apply -k . -n applications
  #         kubectl rollout status deployment/resume -n applications
