name: Deploy Docker image

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Build image)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: kalkutin.dev
          script_stop: true
          script: |
            if [ ! -d "resume" ]; then git clone https://github.com/ecalcutin/resume.git resume; fi
            cd ~/resume
            git pull
            docker compose up --build --force-recreate --no-deps -d
