name: Build and deploy

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ecalcutin/kalkutin.dev
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:$GITHUB_SHA .
          docker push ${{ env.IMAGE_NAME }}:$GITHUB_SHA
  deploy-to-cluster:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.32.4
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: https://cluster.kalkutin.dev:6443
          k8s-secret: ${{ secrets.KUBE_TOKEN }}
      - name: Deploy to cluster (dev)
        run: |
          cd k8s/overlays/dev
          kustomize edit set image $IMAGE_NAME=ecalcutin/kalkutin.dev:$GITHUB_SHA
          kubectl apply -k . -n applications
          kubectl rollout status deployment/resume -n applications
