name: Build and deploy

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ecalcutin/kalkutin.dev
  K8S_NAMESPACE: resume

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}
  deploy-to-cluster:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to cluster (dev)
        run: |
          cd k8s/overlays/dev
          kustomize edit set image IMAGE_NAME:$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/resume -n $K8S_NAMESPACE
