name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy (Build image)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: kalkutin.dev
          script: |
            cd ~/resume && git pull || git clone https://github.com/ecalcutin/resume.git resume
            cd ~/resume
            docker build -t resume .
