name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Build image)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: kalkutin.dev
          script_stop: true
          script: |
            if [ ! -d "resume" ]; then git clone https://github.com/ecalcutin/resume.git resume; fi
            cd ~/resume
            git fetch
            git reset --hard origin/${{github.event.pull_request.head.ref }}
            docker compose up --build --force-recreate --no-deps -d